name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0
      
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push simple-api Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./simple-api
        file: ./simple-api/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-api:latest
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Build and push database Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./database
        file: ./database/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Build and push http-server Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./http-server
        file: ./http-server/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/http-server:latest
        push: ${{ github.ref == 'refs/heads/main' }}
        
  


       
