name: Java CI with Maven and Docker Build

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=alinaghania_devops-livecoding -Dsonar.organization=alinaghania -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'  # This ensures the job runs only on the main branch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push simple-api Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./simple-api
        file: ./simple-api/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-api:latest
        push: true

    - name: Build and push database Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./database
        file: ./database/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
        push: true

    - name: Build and push http-server Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./http-server
        file: ./http-server/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/http-server:latest
        push: true


   
